version: '2'

services:

  oxid6_apache:
    build: container/apache_php7/.
    hostname: ${DOMAIN}
    restart: always
    depends_on:
      - oxid6_mysql
    volumes:
      - ${PWD}/data/www/:/var/www/html/
    ports:
      - ${HTTP_PORT}:80
    links:
      - oxid6_mailhog:mail.server
      
  oxid6_mysql:
    image: mysql:5.7
    hostname: mysql.${DOMAIN}
    restart: always
    volumes:
      - ${PWD}/data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - ${MYSQL_PORT_EXPOSED}:3306

  oxid6_mailhog:
    hostname: mailhog.${DOMAIN}
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_WEB_PORT}:8025
