version: '2'

services:
  oxid6_apache:
    build: container/apache_php7/.
    container_name: oxid6_apache
    restart: always
    volumes:
      - ${PWD}/data/www/:/var/www/html/
    ports:
      - ${HTTP_PORT}:80
      
  oxid6_mysql:
    image: mysql:5.7
    container_name: oxid6_mysql
    restart: always
    volumes:
      - ${PWD}/data/mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    ports:
      - 127.0.0.1:${MYSQL_PORT_EXPOSED}:3306